### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by baneeishaque** [Namdrib/Genius_Scrape#17]

**Comment by Namdrib** [comment]
Just so I can verify it's broken and later verify it works, what did you try running? Eg what artist/song combination, and what command line arguments did you try?
Could you also show any exceptions/errors that you get when you run it?

I'll look into this when I can

Thanks

**Comment by Namdrib** [comment]
After more testing, I've noticed an issue with the lyric returns
Sometimes the song search itself is successful (no errors), but outputs nothing (whether by stdout or clipboard)
Sometimes it does work though
Not sure why it is inconsistent

See if it works for you if you try the same thing several times

**Comment by Namdrib** [comment]
Was that good enough for your needs?
If no further action is required I'll close the issue in two days from now

**Comment by Namdrib** [comment]
Issue seems to be resolved, or at least the workaround of trying again is good enough
Closing issue
